function(_calm_init_library _lib_name)
    if (ARGN)
        set(_alt_lib_name ${ARGN})
    else()
        set(_alt_lib_name ${_lib_name})
    endif()
    get_property(_current_dir GLOBAL PROPERTY _CURRENT_CMAKE_DIR)
    _calm_find_package(Boost ${_git_tag} REQUIRED COMPONENTS ${_alt_lib_name})
    if (NOT TARGET boost_${_lib_name})
        calm_add_library(boost_${_lib_name} INTERFACE
                INCLUDES $<BUILD_INTERFACE:${Boost_INCLUDE_DIRS}/include>;$<INSTALL_INTERFACE:include>
                DEPENDENCIES ${_deps}
                NAMESPACE Boost
                EXPORT_NAME ${_lib_name}
                )
    endif()
    get_target_property(_type boost_${_lib_name} TYPE)
    if (_type STREQUAL INTERFACE_LIBRARY)
        get_target_property(_out boost_${_lib_name} INTERFACE_LINK_LIBRARIES)
    else()
        get_target_property(_out boost_${_lib_name} LINK_LIBRARIES)
    endif()
    foreach(_dep ${_out})
        string(SUBSTRING ${_dep} 0 7 _namespace)
        if (_namespace STREQUAL "Boost::")
            string(SUBSTRING ${_dep} 7 -1 _dep)
            message(STATUS "including ${_current_dir}/build-modules/Boost/${_dep}.cmake for Boost::${_lib_name}")
            include(${_current_dir}/build-modules/Boost/${_dep}.cmake)
        elseif(_namespace STREQUAL "$<LINK_")
            string(LENGTH "${_dep}" _len)
            math(EXPR _len "${_len} - 20")
            string(SUBSTRING ${_dep} 19 ${_len} _dep)
            message(STATUS "including ${_current_dir}/build-modules/Boost/${_dep}.cmake for Boost::${_lib_name}")
            include(${_current_dir}/build-modules/Boost/${_dep}.cmake)
        endif()
    endforeach()
endfunction()

