if (NOT TARGET boost_move)
    set(_lib_name move)
    set(_lib_alt_name headers)
    set(_dependencies assert core static_assert config)
    include(${_current_dir}/build-modules/Boost/internal.cmake)
endif()
