if (NOT TARGET boost_preprocessor)
    project(boost_preprocessor VERSION 1.74.0)
    _calm_find_package(Boost ${_git_tag} REQUIRED COMPONENTS preprocessor)

    bcm_setup_version(VERSION 1.74.0)
    add_library(boost_preprocessor INTERFACE)
    add_library(Boost::preprocessor ALIAS boost_preprocessor)
    set_property(TARGET boost_preprocessor PROPERTY EXPORT_NAME preprocessor)
    bcm_deploy(TARGETS boost_preprocessor INCLUDE include NAMESPACE Boost::)
endif()